version: '3.9'

networks:
  progettoverifica:
    driver: bridge
volumes:
  db:
  
services:
    tomcat:
      build: .
      image: 8-jdk8-openjdk
      container_name: tomcatcontainer
      ports:
      - "8080:8080"
      depends_on:
      - db
      networks:
      - progettoverifica

    db:
      build: ./postgresql
      image: postgres
      container_name: postgresqlcontainer
      volumes:
       - db:/var/lib/postgresql/data
       - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      ports:
      - 5432:5432
      deploy:
        placement:
          constraints: [node.role==contact]
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: polaroid
        
      networks:
      - progettoverifica


     
     